global:
  scrape_interval: 15s   # Scrape data every 15 seconds
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'chat-websocket'
    static_configs:
      - targets: ['host.docker.internal:8080']   # Adjust according to your service's actual address
